# disease_translator.py

TRANSLATIONS = {
    "Apple___Apple_scab": "🍎 Парша яблони",
    "Apple___Black_rot": "🍎 Черная гниль яблони",
    "Apple___Cedar_apple_rust": "🍎 Ржавчина яблони",
    "Apple___healthy": "🍎 Яблоня здорова",
    "Blueberry___healthy": "🫐 Голубика здорова",
    "Cherry_(including_sour)___Powdery_mildew": "🍒 Мучнистая роса вишни",
    "Cherry_(including_sour)___healthy": "🍒 Вишня здорова",
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot": "🌽 Церкоспороз кукурузы",
    "Corn_(maize)___Common_rust_": "🌽 Обыкновенная ржавчина кукурузы",
    "Corn_(maize)___Northern_Leaf_Blight": "🌽 Северный гельминтоспориоз кукурузы",
    "Corn_(maize)___healthy": "🌽 Кукуруза здорова",
    "Grape___Black_rot": "🍇 Черная гниль винограда",
    "Grape___Esca_(Black_Measles)": "🍇 Эска винограда",
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": "🍇 Пятнистость листьев винограда",
    "Grape___healthy": "🍇 Виноград здоров",
    "Orange___Haunglongbing_(Citrus_greening)": "🍊 Хуанлунбин (позеленение цитрусовых)",
    "Peach___Bacterial_spot": "🍑 Бактериальная пятнистость персика",
    "Peach___healthy": "🍑 Персик здоров",
    "Pepper,_bell___Bacterial_spot": "🫑 Бактериальная пятнистость перца",
    "Pepper,_bell___healthy": "🫑 Перец здоров",
    "Potato___Early_blight": "🥔 Альтернариоз картофеля",
    "Potato___Late_blight": "🥔 Фитофтороз картофеля",
    "Potato___healthy": "🥔 Картофель здоров",
    "Raspberry___healthy": "🍇 Малина здорова",
    "Soybean___healthy": "🌱 Соя здорова",
    "Squash___Powdery_mildew": "🎃 Мучнистая роса тыквенных",
    "Strawberry___Leaf_scorch": "🍓 Красная пятнистость клубники",
    "Strawberry___healthy": "🍓 Клубника здорова",
    "Tomato___Bacterial_spot": "🍅 Бактериальная пятнистость томата",
    "Tomato___Early_blight": "🍅 Альтернариоз томата",
    "Tomato___Late_blight": "🍅 Фитофтороз томата",
    "Tomato___Leaf_Mold": "🍅 Кладоспориоз томата",
    "Tomato___Septoria_leaf_spot": "🍅 Септориоз томата",
    "Tomato___Spider_mites Two-spotted_spider_mite": "🍅 Паутинный клещ",
    "Tomato___Target_Spot": "🍅 Целевая пятнистость томата",
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": "🍅 Вирус желтой курчавости томата",
    "Tomato___Tomato_mosaic_virus": "🍅 Вирус табачной мозаики томата",
    "Tomato___healthy": "🍅 Томат здоров",
}

def translate(label: str) -> str:
    """Возвращает русское название болезни."""
    return TRANSLATIONS.get(label, label.replace('_', ' ').title())
